### ISSUE TITLE
If title, source, and destination options are included, apple-maps may fail to display directions

### ISSUE THREAD

**Issue by acoulon99** [flexible-agency/react-native-map-link#113]
When I include source and destination lat/lng along with a title as options, apple-maps attempts to lookup the title as the destination. If the title is a custom name and apple-maps is unable to find it as a location, a "no results found" state is reached, and no directions are displayed.

I believe this is caused by line 72 within `src/index.js`:

```
url += `&q=${title ? `${encodedTitle}&address=${encodedTitle}` : 'Location'}`
```

It seems as though the title is being treated as an address.

![image](https://user-images.githubusercontent.com/9921114/69902278-4474b780-1351-11ea-850c-bd7b51583254.png)

**Comment by tschoffelen** [comment]
I believe there's some history behind this, but I don't really remember what.

So feel free to submit a PR to fix this behaviour!

**Comment by acoulon99** [comment]
@tschoffelen, sounds good! I'll create a fork and see what I can come up with :)

**Comment by maxxwellfirth** [comment]
@acoulon99 did you manage to find a solution? I also just came across this bug - when all four lat/long parameters are set, Apple Maps will use the `title` variable if it is set, as opposed to the lat/long variables. The only solution I have right now is to remove the value for `title`, which is not ideal

cc: @tschoffelen

**Comment by chrise86** [comment]
Google Maps also seems to use the title.

**Comment by tschoffelen** [comment]
Possibly, removing the `address` parameter will resolve this, as @acoulon99 in the issue description, but I haven't had time to verify this yet, and am unsure how this might impact current users of the library.

If anybody could do some testing or find some documentation related to the parameter, that would be super helpful.

**Comment by Aryk** [comment]
Hey guys...maybe a simple low-risk solution would be to add appleForceLatLon since we already set that precedent  with googleForceLatLon?

It's really a bad experience for google maps to suffer because we can't specify title without screwing up Apple... lol

> Google Maps also seems to use the title.
> 
> EDIT: I guess that's why `googleForceLatLon` exists 🤦

**Comment by Aryk** [comment]
Alright...I did some research:

https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

It's actually super confusing, 

For "q":

> The query. This parameter is treated as if its value had been typed into the Maps search field by the user. Note that q=* is not supported
> **The q parameter can also be used as a label if the location is explicitly defined in the ll or address parameters.**

For "address":

> The address. Using the address parameter simply displays the specified location, it does **not** perform a search for the location.

I did some testing without having a source destination...and seems to be working without `address`.

**Comment by Aryk** [comment]
@tschoffelen my PR is approved...but how does it actually get merged in?
