### ISSUE TITLE
Build failures in latest version - 2.7.14

### ISSUE THREAD

**Issue by rakeshmaddala87** [flexible-agency/react-native-map-link#147]
Hello,

We are facing below issue when built with latest release 2.7.14

FAILURE: Build failed with an exception.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
* What went wrong:
Use '--warning-mode all' to show the individual deprecation warnings.
Execution failed for task ':app:mergeUatReleaseResources'.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
> 1 exception was raised by workers:
819 actionable tasks: 368 executed, 451 from cache
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  android/app/build/generated/res/react/uat/release/drawable-mdpi/node_modules_reactnativemaplink_src_images_gett.png: error: failed to read PNG signature: file does not start with PNG signature.
  android/app/build/generated/res/react/uat/release/drawable-mdpi/node_modules_reactnativemaplink_src_images_gett.png: error: file failed to compile.

Currently we reverted back to version one lower(2.7.13) and went ahead.
Just dropping a note here, so it may help others.

Thanks,
Rakesh Maddala

**Comment by tschoffelen** [comment]
Thanks for pointing this out!

I've just released `2.7.15` with a new image for Gett, could you give that version a try?
