### ISSUE TITLE
Is it ok to add a dependency?

### ISSUE THREAD

**Issue by eaTnuG** [flexible-agency/react-native-map-link#150]
First, thanks for the great tool. It really helped me a lot. 

I'm now building an app which will soon go public in Korea. And in Korea, the Naver Map([ios](https://apps.apple.com/us/app/naver-map-navigation/id311867728),[android](https://play.google.com/store/apps/details?id=com.nhn.android.nmap&hl=ko)) is the most popular among map applications. So I'm trying to add linking logic to this library. But this Naver Map wants to specify appname of the caller app ( applicationId in android, bundle identifier in ios ). I think it's possible to pass that information via [react-native-device-info](https://github.com/react-native-community/react-native-device-info). 

Is it ok to add dependency to this? or could you suggest me the other way to provide that infos to Naver Map?

**Comment by eaTnuG** [comment]
or is it ok to add showLocation options specific to naver map?

**Comment by tschoffelen** [comment]
Hi! I think adding a dependency with native code is not really a great idea just to support one app, so I'd rather add a separate key to the `showLocation` options

**Comment by eaTnuG** [comment]
thanks for the response. I've done it and sent pr here(https://github.com/flexible-agency/react-native-map-link/pull/151#issue-489686755)
