### ISSUE TITLE
Add support work specifying directions mode: walk, car, bike

### ISSUE THREAD

**Issue by pke** [flexible-agency/react-native-map-link#152]
Could that be another generalised property that gets converted individually for each provider?

**Comment by tschoffelen** [comment]
Sounds like a great idea!

**Comment by pke** [comment]
Ok, I know the args for gmaps and apple-maps. Will check with the others where it makes sense.

**Comment by tomLadder** [comment]
Hey @pke Any news on this?

**Comment by pke** [comment]
Didn't have time last year anymore. When its more relaxed I might provide a PR

**Comment by erickriva** [comment]
Take a look at #195
