### ISSUE TITLE
Allow iOS to navigate directly to apple maps instead of routing through safari first

### ISSUE THREAD

**Issue by salocinhawk** [flexible-agency/react-native-map-link#153]
I noticed while using this that Apple Maps first opens safari then opens Apple Maps. I checked the `constants.js` file to see what the `apple-prefix` was and noticed this line in the `generatePrefixes` function: 

`'apple-maps': isIOS ? 'http://maps.apple.com/' : 'applemaps://',`

My proposal is that you can prefix on iOS with `maps://` instead of the url and it will navigate to the Apple Maps app without routing through safari. i.e. 
`'apple-maps': isIOS ? 'maps://' : 'applemaps://',`

I'll fork the project and create a PR for review.

**Comment by tschoffelen** [comment]
Thanks for the PR!
