### ISSUE TITLE
Some changes after the latest release

### ISSUE THREAD

**Issue by vvscode** [flexible-agency/react-native-map-link#162]
Both after the changes from https://github.com/flexible-agency/react-native-map-link/pull/158/

1) now on opening the link it asks which app should be used (and if default handler for geo is not google map it might open that app instead of gmaps)

2) on opening google maps it doesn't show the route

**Comment by jblancoh** [comment]
@vvscode 
I have same issues.
When I try to open google maps this open with this url "geo:?" instead of "https://maps.google.com/"

I don't have the uber app

Temporal solution:
Fork and remove condition for "geo:?" or Rollback version.
