### ISSUE TITLE
Refactoring requests

### ISSUE THREAD

**Issue by vvscode** [flexible-agency/react-native-map-link#166]
I went to the code to make a PR with 2gis navigator, but after playing with it I have a proposal:

0) TS is nice to have, for sure =)
1) can we split `showLocation` to a per-app URL generator? I see currently a number of cases, but adding the new app doesn't have any nice way to do the new app.

**Comment by tschoffelen** [comment]
I like your second idea! Definitely would be good, that function is becoming quite complicated now that we support so many navigation apps...

TypeScript could be nice too, but personally wouldn't have too much of a priority for me.

**Comment by vvscode** [comment]
that is more a question, if you're open for PR's in that direction?

**Comment by tschoffelen** [comment]
Certainly!

**Comment by vvscode** [comment]
According to my failure in the next PR -, what are the general approaches to test the package?

Or first it worth to make a PR with some unit tests?

**Comment by tschoffelen** [comment]
Yeah, that might be helpful. The current tests are very minimal :)

**Comment by vvscode** [comment]
@tschoffelen  are you fine with PR to migrate code to TS?

**Comment by tschoffelen** [comment]
PR: #175
