### ISSUE TITLE
Some code formatting issues

### ISSUE THREAD

**Issue by vvscode** [flexible-agency/react-native-map-link#168]
I don't see any linter rules, prettier etc in the project. On saving `index.js` file I have next changes

![image](https://user-images.githubusercontent.com/6904368/111002544-b29e8b80-8396-11eb-8dfd-e65d1be1107c.png)

and they look legit for me. Shouldn't we add some rules about the code + github actions setup ?

**Comment by tschoffelen** [comment]
Ran eslint, and made this a requirement for new PRs.
