### ISSUE TITLE
Show map location when useSourceDestiny is empty instead direction

### ISSUE THREAD

**Issue by dungle-groove** [flexible-agency/react-native-map-link#185]
I try this library with Google Maps but it could not display the location when the route path is too long. If useSourceDestiny is empty, it should be show a map view instead a map direction

**Comment by theneekz** [comment]
the url should be `https://www.google.com/maps/**search**/?api=1` and if you don't useSourceDestiny `&**query**=35.321386,-80.209822`.

**Comment by theneekz** [comment]
[see my patch](https://github.com/flexible-agency/react-native-map-link/issues/200#issue-1010135195)

**Comment by tschoffelen** [comment]
Fixed in #201
