### ISSUE TITLE
iOS Apple Maps issue

### ISSUE THREAD

**Issue by rollsroyc3** [flexible-agency/react-native-map-link#188]
I've noticed an issue with Apple Maps when calling the following:

```showLocation({app: 'apple-maps', latitude: 39.1160797, longitude: -84.5732168})```

At first I get the preview that shows the pin on the correct address, but you can see in the Address section on the screenshot below it has already gotten rid of the street number (1255 Ross Ave Cincinnati Ohio which you can confirm on the Desktop version of Apple Maps using above lat and lng.).

https://www.dropbox.com/s/u7m6hgzamm23fwn/Screen%20Shot%202021-06-29%20at%203.07.52%20PM.png?dl=0

And then when I click`Directions` it creates a 2nd marker with the generic street location.

https://www.dropbox.com/s/t23tugqu04xool6/Screen%20Shot%202021-06-29%20at%203.15.43%20PM.png?dl=0

Anyone run into this or maybe I'm just doing something wrong?

**Comment by rollsroyc3** [comment]
I upgraded to the latest version
 "react-native-map-link": "^2.7.28",

And I am testing on iOS Simulator running 14.5

**Comment by rollsroyc3** [comment]
Logging the output from the showLocation function I get ```maps://?ll=39.1160797,-84.5732168&q=Location```

If I hardcode this it works ```maps://?q=39.1160797,-84.5732168``` so not sure if its just an issue with ios maps, or something im doing wrong but I guess Ill fork and change it.

**Comment by srudberg** [comment]
We are seeing the same issue and only with Apple maps.   Preview shows the right pin location (and lat/long) but when you click directions, it gets directions to a different lat/long on the same street.  It's like it is doing a reverse geo on the lat/long to get the address, then taking the street (without the house number) and geocoding the street location (without house number) and then giving directions to the street lat/long

**Comment by mgithubmessier** [comment]
Think I found a solution after looking at your comment @rollsroyc3. After reading some of [apple's map scheme reference](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html), it's looking like this library should be using the `sll` parameter, not the `ll` parameter.

I tested that locally and it worked well, so I'll open a PR to this library momentarily.

**Comment by mgithubmessier** [comment]
This is the PR
https://github.com/flexible-agency/react-native-map-link/pull/207

**Comment by tschoffelen** [comment]
Fixed in #207 - thanks @mgithubmessier!

**Comment by guvenakcoban** [comment]
#207 

`q` parameter meaning from [Scheme Ref](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html)
> The q parameter can also be used as a label if the location is explicitly defined in the ll or address parameters.

Here it says: parameter q is using as label when it is with 'll' or 'address'. So, what would happen with `sll`?

I'm facing issues about that.

If I run this code:

```
showLocation({
      latitude: 36.99941581,
      longitude: 28.4613709,
      title: 'Tura',
      googleForceLatLon: true,
});
```

Apple Maps shows the Tura which is a town in India but the lat, lng is in Turkey.

**Comment by mgithubmessier** [comment]
@guvenakcoban @tschoffelen 
I feel that we should be allowing the user to provide the sll query parameter as an option still. 

A localized search even for normal street address text is very useful because you can't provide a title to it if you only provide lat/lng at this junction. How would you both feel about it if I added an option called `appleLocalizedLatLon` as well, which replaces instead of ignoring the existing latlong options if provided? That way we can have our cake and eat it too for the folks who want to provide a specific latlon.
