### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by dan-iliescu** [flexible-agency/react-native-map-link#191]
Is there any foreign language support or are there any plans to implement it in the future? Thank you.

**Comment by tschoffelen** [comment]
There is not too much text in the library - the dialog title and message can already be customised via the `options` object that is passed into `showLocation()`

Happy to see how you think that could be improved!

**Comment by tschoffelen** [comment]
Closing this for now, as it is already possible to customise most of the text. Happy to accept PRs to improve this system though!
