### ISSUE TITLE
Google Maps not in list even though installed in Expo debugger

### ISSUE THREAD

**Issue by jmbeach** [flexible-agency/react-native-map-link#197]
For some reason, Google Maps only shows up in my list whenever I deploy a production build. I want to see it even when I'm using the Expo debugger. All I can see is Apple Maps and Waze.

Any ideas what would cause this?

This is in my app.json

```json
"infoPlist": {
    "LSApplicationQueriesSchemes": [
      "comgooglemaps",
      "apple-maps",
      "waze"
    ]
  }
```

**Comment by jmbeach** [comment]
Also, here's my code where I actually open the list:

```ts
showLocation({
  latitude: selectedBusiness.geometry.location.lat,
  longitude: selectedBusiness.geometry.location.lng,
  title: selectedBusiness.name,
});
```

**Comment by jmbeach** [comment]
Oh and I'm on version 2.8.0

**Comment by jmbeach** [comment]
Oh, just noticed the `alwaysIncludeGoogle` option. Google maps shows up when I include that. Should probably show up either way, right?

**Comment by tschoffelen** [comment]
Hi Jared! Unfortunately that's due to the fact that your infoPlist changes in app.json only take effect when you build your own app. The Expo preview app has a set Info.plist that can't be dynamically changed.
