### ISSUE TITLE
No map application loaded on Popup

### ISSUE THREAD

**Issue by nzwnabdulwahid** [flexible-agency/react-native-map-link#205]
Hello everyone, I am using `"react-native-map-link": "^2.7.19"` and today after a new release, some of the android's phone are not showing any map application - and it is confirmed the devices have at least Google Maps or Waze installed.

This are the snippet for the popup
```
 <Popup
    modalProps={{          
       animationIn: 'slideInUp',
    }}
    options={{
      latitude:
        routeDataInternal[currentActiveLocationIndex].coordinates.latitude,
      longitude:
        routeDataInternal[currentActiveLocationIndex].coordinates.longitude,
    }}
  />
```

It is confirmed that both latitude and longitude are not undefined or null. 

Is there any way I could debug this further ?

**Comment by tschoffelen** [comment]
Hi there! Are you sure you've followed the post-install steps from the README to whitelist these apps?
